package com.example.kotlintv.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize
//import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "continuewatch_table") // User Entity represents a table within the database.
data class ContinueWatch(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val contentId: Int,
    val lastWatchDuration: Long,
    val totalDuration: Long
): Parcelable